dist: precise
language: rust
cache: cargo
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libmagic1 libmagic-dev
