[package]
name = "cratesfyi"
version = "0.3.0"
authors = ["Onur Aslan <onuraslan@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/onur/cratesfyi"
build = "build.rs"

[dependencies]
log = "0.3"
rustc-serialize = "0.3"
regex = "0.1"
postgres = { version = "0.11", features = [ "time", "rustc-serialize" ] }
clap = "2"
crates-index-diff = "2"
git2 = "0.4"
time = "0.1"
hyper = "0.9"
semver = "0.5"
slug = "=0.1.1"
env_logger = "0.3"
magic = "0.12"
r2d2 = "0.7"
r2d2_postgres = "0.10"
url = "1.2"
libc = "0.2"
hoedown = "5.0"
badge = { version = "0", path = "src/web/badge" }
error-chain = "0.5"

# iron dependencies
iron = "0.5"
router = "0.5"
handlebars-iron = "0.22"
params = "0.6"

# iron-0.5 compatible staticfile
# TODO: WIP upstream patch: https://github.com/iron/staticfile/pull/91
# This requires iron-test crate to be compatible with iron-0.5
[dependencies.staticfile]
git = "https://github.com/onur/staticfile.git"
branch = "iron-0.5"
features = [ "cache" ]

[dependencies.cargo]
git = "https://github.com/rust-lang/cargo.git"
rev = "f6500c6b6480c89492773bff6d41c4abf6c5ee15"

[dev-dependencies]
tempdir = "0.3"

[build-dependencies]
time = "0.1"
sass-rs = "0.0.18"

[[bin]]
name = "cratesfyi"
test = false
doc = false
